config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'profile', action: :show, controller: 'users'
  resources :users, only: [:index]
  resources :friend_requests, :friends,  only: [:index, :create, :destroy]
  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :comments do
    resources :likes, only: [:create, :destroy]
  end
  devise_for :users, :controllers => { :registrations => "users/registrations", omniauth_callbacks: "users/omniauth_callbacks"  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body, presence: true
  has_many :likes, as: :likable
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :user, uniqueness: { scope: :friend, message: 'Already Friends' }
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  validates :sender, uniqueness: { scope: :receiver, message: 'Friend request already sent' }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likable, polymorphic: true
  belongs_to :user

  validates :user, uniqueness: { scope: :likable, message: 'Already liked this' }
end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  has_many :comments
  has_many :likes, as: :likable
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates :username, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts
  has_many :comments
  has_many :sent_friend_requests, class_name: 'FriendRequest', foreign_key: :sender
  has_many :friend_requests, foreign_key: :receiver
  has_many :friends, ->(user) { unscope(:where).where('user_id = ? OR friend_id = ?', user.id, user.id) }
  has_many :likes

  devise :omniauthable, omniauth_providers: %i[github]
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find params[:post_id]
    @comment = @post.comments.build
  end

  def create
    @post = Post.find params[:post_id]
    @comment = current_user.comments.new(comments_params)
    @comment.post = @post
    if @comment.save
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  def index
    @friend_requests = current_user.friend_requests
  end

  def create
    sender = User.find(params[:sender_id])
    receiver = User.find(params[:receiver_id])
    puts receiver
    fr = current_user.friend_requests.build(sender: sender, receiver: receiver)
    fr.save
  end

  def destroy
    friend_request = FriendRequest.find(params[:id])
    friend_request.destroy
    redirect_to friend_requests_path
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = current_user.friends
  end

  def create
    friend = User.find(params[:friend])
    new_friend = current_user.friends.build(friend: friend)
    new_friend.save
    redirect_to friends_path
  end

  def destroy
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id]) if params[:post_id]
    comment = Comment.find(params[:comment_id]) if params[:comment_id]
    like = current_user.likes.new(likable: post) if params[:post_id]
    like = current_user.likes.new(likable: comment) if params[:comment_id]
    like.save
  end

  def destroy
    like = Like.find(params[:id])
    if like.destroy
      flash[:success] = 'like was successfully deleted.'
    else
      flash[:error] = 'Failed to delete the like.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(posts_params)
    if @post.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to root }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def posts_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    if @user.persisted?
      UserMailer.with(user: @user).welcome_email.deliver_now
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<% if comment.errors.any? %>
  <% comment.errors.full_messages.each do |msg| %>
    <div class="error-message">
      <%= msg %>
    </div>
  <% end %>
<% end %>


<%= form_with model: [post, comment] do |form| %>
<div class="comment-form">
  <%= form.text_area :body, placeholder: 'What do you think of this?', size: "70x5", class: "comment-input" %>
  <%= form.submit class: "comment-submit-button" %>
</div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "comments", @comment %>

app/views/comments/new.html.erb
<%= turbo_frame_tag "new_comment" do %>
  <p>Comment as: <%= current_user.username %></p>
  <%= render "form", post: @post, comment: @comment%>
<% end %>

app/views/friend_requests/create.html.erb
<h1>FriendRequests#create</h1>
<p>Find me in app/views/friend_requests/create.html.erb</p>

app/views/friend_requests/destroy.html.erb
<h1>FriendRequests#destroy</h1>
<p>Find me in app/views/friend_requests/destroy.html.erb</p>

app/views/friend_requests/index.html.erb
<h1>Friend requests</h1>
<% @friend_requests.each do |friend_request| %>
  <%= friend_request.sender.username %>
  <%= form_with url: friends_path, method: :post do |form| %>
    <%= form.hidden_field :user, value: friend_request.receiver.id %>
    <%= form.hidden_field :friend, value: friend_request.sender.id %>
    <%= form.submit 'Accept' %>
  <% end %>
  <%= form_with url: friend_request_path(friend_request) , method: :delete do |form| %>
    <%= form.submit 'Decline' %>
  <% end %>
<% end %>

app/views/friends/index.html.erb
<h1>Friends</h1>
<% @friends.each do |friend| %>
  <%= friend.friend.username %><br>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <%= form.text_area :body, placeholder: 'What do you want to share today?', size: "70x5" %> <br>
  <%= form.submit 'Post' %>
<% end %>
<% if post.errors.any? %>
  <ul>
    <% post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/posts/_like.html.erb
<div class="like-button" data-controller="like"
  data-like-imagel-value=<%=asset_path('heart-filled.png')%>
  data-like-imageu-value=<%=asset_path('heart.png')%>
  data-like-count-value=<%= post.likes.count%>
>
  <div class="like-image" data-action="click->like#toggle">
      <% if current_user.likes.map(&:likable_id).include?(post.id) %>
        <% like = post.likes.where(user_id: current_user.id)%>
        <%= form_with url: post_like_path(post.id, id: like.first.id ), method: :delete do |form| %>
          <%= form.submit "", :type => :image, :src => asset_path('heart-filled.png'), class: 'liked', 'data-like-target': :like %>
        <% end %>
      <% else %>
        <%= form_with url: post_likes_path(post.id), method: :post do |form| %>
          <%= form.submit "", :type => :image, :src => asset_path('heart.png'), class: 'unliked', 'data-like-target': :like%>
        <% end %>
      <% end %>
  </div>
  <div>
    <span class="likes-count" data-like-target="counter" ><%= post.likes.count %></span> 
    like
  </div>
</div>

app/views/posts/_nav.html.erb
<div class="navbar-container">
  <div class="navbar">
    <div class="nav-left">
        <div class="logo">
          <%= link_to root_path do %>
            <%= image_tag ('sociwave-icon.png') %>
            <p>SociWave</p>
          <% end %>
        </div>
    </div>
    <div class="nav-right">
      <div class="messages">
        <%=link_to image_tag 'messages.png'%>
      </div>
      <div class="notifications">
        <%=link_to image_tag 'notification.png'%>
      </div>
      <div data-controller="visibility" data-visibility-show-class="show">
        <div class="user-container">
          <div class="user", data-action="click->visibility#toggle">
            <%=image_tag 'user.png'%>
          </div>
          <div class="user-dropdown", data-visibility-target="dropdown">
            <%= link_to "Profile", profile_path %>
            <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: 'logout-link' do%>
              <%= image_tag 'logout.png' %>
              Logout
             <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
  <div id="<%= dom_id post %>">
    <div class="post-item">
      <%= link_to post_path(post) do %>
        <div class="item-head">
          <span class="user-image">
            <%= image_tag('user.png')%>
          </span>
          <span class="username">
            <%= post.user.username %>
          </span>
          <% time = Time.at(Time.now - post.created_at) %>
          <% days = time.utc.strftime("%e") %>
          <% hours = time.hour %>
          <% mins = time.min %>
          <% if (hours - 1) <= 0 && (days.to_i - 1) <= 0 %>
            <%= mins %> minutes ago
          <% elsif (days.to_i - 1) == 0 %>
            <%= hours %> hours ago
          <% else %>
            <%= (days.to_i - 1)%> days ago
          <% end %>
        </div>
        <div class="item-body">
          <%= post.body %> <br>
        </div>
      <% end %>
      <div class="item-buttons">
        <%= render partial: 'like', locals: {post: post}%>
        <%= link_to post_path(post) do %>
          <div class="comment-buttons">
            <%= image_tag('comment.png') %> <br>
            <%= post.comments.count %> Comments
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.append('post-display', partial: 'post', locals: { post: @post }) %>

app/views/posts/index.html.erb
<%= render partial: 'nav'%>
<section class="add-post-container">
  <div class="post-form">
    <%= turbo_frame_tag 'new_post', src: new_post_path %>
  </div>
</section>
<section class="post-display-container">
  <h1>Timeline</h1>
  <div id="post-display">
    <%= render partial: 'post', collection: @posts %>
  </div>
</section>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= turbo_frame_tag "new_post" do %>
  <%= render "form", post: @post%>
<% end %>

app/views/posts/show.html.erb
<%= render partial: 'nav' %>
<div class="post-display-container">
  <div class="post-item">
    <div class="item-head">
      <span class="user-image">
        <%= image_tag('user.png')%>
      </span>
      <span class="username">
        <%= @post.user.username %>
      </span>
      <% time = Time.at(Time.now - @post.created_at) %>
      <% days = time.utc.strftime("%e") %>
      <% hours = time.hour %>
      <% mins = time.min %>
      <% if (hours - 1) <= 0 && (days.to_i - 1) <= 0 %>
        <%= mins %> minutes ago
      <% elsif (days.to_i - 1) == 0 %>
        <%= hours %> hours ago
      <% else %>
        <%= (days.to_i - 1)%> days ago
      <% end %>
    </div>
    <div class="item-body">
      <%= @post.body %> <br>
    </div>
  
    <div class="item-buttons">
      <%= render partial: 'like', locals: {post: @post}%>
      <div class="comment-buttons">
        <%= image_tag('comment.png') %> <br>
        Comment
      </div>
    </div>

    <div class="comments-container">
      <div class="comment-item">
        <%= turbo_frame_tag "new_comment", src: new_comment_path(post_id: @post.id), target: "_top"%>
      </div>
      <% @post.comments.each do |comment| %>
        <div class="comment-item">
          <div class="comment-head">          
            <span class="user-image">
            <%= image_tag('user.png')%>
            </span>
            <span class="username">
              <%= comment.user.username %>
            </span>
            <% time = Time.at(Time.now - comment.created_at) %>
            <% days = time.utc.strftime("%e") %>
            <% hours = time.hour %>
            <% mins = time.min %>
            <% if (hours - 1) <= 0 && (days.to_i - 1) <= 0 %>
              <%= mins %> minutes ago
            <% elsif (days.to_i - 1) == 0 %>
              <%= hours %> hours ago
            <% else %>
              <%= (days.to_i - 1)%> days ago
            <% end %>
          </div>
          <div class="comment-body">
            <%= comment.body%> <br>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |user| %>
  <%= user.username %>  
  <% if current_user == user %>
    <span>(me)</span>
  <% elsif current_user.sent_friend_requests.exists?(receiver_id: user.id) %>
    <span>(request sent)</span>
  <% else %>
    <%= form_with url: friend_requests_path , method: :post do |form| %>
      <%= form.hidden_field :sender_id, value: current_user.id %>
      <%= form.hidden_field :receiver_id, value: user.id %>
      <%= form.submit 'Send friend request' %>
    <% end %>
  <% end %> <br>
  
<% end %>

app/views/users/show.html.erb
<%= render 'posts/nav'%>
<div class="profile-container">
  <div class="profile-section">
    <div>Profile</div>
  </div>
  <div class="profile-section">
    <div>Post</div>
    <% current_user.posts.each do |post| %>
      <%=post.body%>
    <% end %>
  </div>
  <div class="profile-section">
    <div>Friends</div>
    <% current_user.friends.each do |friend| %>
      <%=friend.username%>
    <% end %>
  </div>
</div>